services:
  traefik:
    image: traefik:3.0
    ports:
      # Listen on port 8010, default for HTTP (Host Nginx should proxy_pass here)
      - 8010:80
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      # HTTP Router (No HTTPS/TLS)
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.${DOMAIN?Variable not set}`)
      # Auth middleware
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
      - traefik.http.routers.traefik-dashboard-http.middlewares=admin-auth
      - traefik.http.routers.traefik-dashboard-http.service=api@internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      # Disable HTTPS/TLS/LE
      # - --entrypoints.https.address=:443
      # - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      # - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
